# Generated by Django 5.0.7 on 2024-08-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_typeprice_alter_nft_cat_nft_tprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='tPrice',
            new_name='typePrice',
        ),
    ]
