# Generated by Django 5.0.7 on 2024-08-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_tprice_nft_typeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='autor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
